name: Publishes new release and prepares for next version

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Release and prepare for next iteration
        uses: qcastel/github-actions-maven-release@master
        with:
          maven-repo-server-id: github
          maven-repo-server-username: ${{ github.actor }}
          maven-repo-server-password: ${{ github.token }}

          gpg-enabled: "false"

          git-release-bot-name: "release-bot"
          git-release-bot-email: "release-bot@example.com"

          access-token: ${{ secrets.GITHUB_TOKEN }}

      # Run the build again for the new tag
      - name: Cleanup previous build
        # Need elevated rights to clean, as previous steps created
        # files owned by a different user than the current user
        run: git reset --hard && sudo git clean -dffx

      - name: Get commits pushed during releasing
        run: git pull

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Publish package
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
